package viewer

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/victor141516/besht/internal/codegen"
)

func TestRenderHidesSourceCommentsAndLeavesGapForExpandedSourceLine(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "main.bsh")
	if err := os.WriteFile(srcPath, []byte("if (ready) console.log(\"yes\")\nconsole.log(\"done\")\n"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	compiled := strings.Join([]string{
		"# Generated by besht -- do not edit by hand",
		"# besht:" + srcPath + ":1:1",
		"# besht:" + srcPath + ":1:1",
		"if [ \"$ready\" = 1 ]; then",
		"    printf '%s\\n' 'yes'",
		"else",
		"    :",
		"fi",
		"# besht:" + srcPath + ":2:1",
		"printf '%s\\n' 'done'",
	}, "\n") + "\n"

	out, err := Render(compiled, 100)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if strings.Contains(out, "# besht:") {
		t.Fatalf("rendered output should hide source comments:\n%s", out)
	}
	lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")
	firstSourceIndex := lineIndexContaining(lines, "if (ready) console.log")
	secondSourceIndex := lineIndexContaining(lines, "console.log(\"done\")")
	if firstSourceIndex < 0 || secondSourceIndex < 0 {
		t.Fatalf("rendered output missing source lines:\n%s", out)
	}
	if secondSourceIndex-firstSourceIndex <= 1 {
		t.Fatalf("expanded source line should leave a left-side gap before the next source line:\n%s", out)
	}
	if countLinesContaining(lines, "if (ready) console.log") != 1 {
		t.Fatalf("duplicate same-line source comments should collapse into one source row:\n%s", out)
	}
	if !strings.Contains(out, "1 | if (ready) console.log") || !strings.Contains(out, "2 | console.log(\"done\")") {
		t.Fatalf("rendered output should include source line numbers:\n%s", out)
	}
	if !strings.Contains(out, "2 | if [ \"$ready\" = 1 ]; then") || !strings.Contains(out, "7 | printf '%s\\n' 'done'") {
		t.Fatalf("rendered output should include visible shell line numbers:\n%s", out)
	}
}

func TestBuildUsesSourceMapsInternallyButDoesNotDisplayThem(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "main.bsh")
	if err := os.WriteFile(srcPath, []byte("let name = \"Ada\"\nconsole.log(name)\n"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	out, err := Build(srcPath, codegen.Options{NoSourceMap: true}, 100)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if strings.Contains(out, "# besht:") {
		t.Fatalf("visualization should not display source comments:\n%s", out)
	}
	if !strings.Contains(out, "1 | let name = \"Ada\"") || !strings.Contains(out, "2 | console.log(name)") {
		t.Fatalf("visualization should map source lines even when NoSourceMap is passed:\n%s", out)
	}
	if !strings.Contains(out, "name='Ada'") || !strings.Contains(out, "printf '%s\\n' \"$name\"") {
		t.Fatalf("visualization should include compiled shell lines:\n%s", out)
	}
}

func TestRenderWithHighlighterColorsBothPanes(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "main.bsh")
	if err := os.WriteFile(srcPath, []byte("let name = \"Ada\"\nconsole.log(name)\n"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	compiled := strings.Join([]string{
		"#!/bin/sh",
		"# besht:" + srcPath + ":1:1",
		"name='Ada'",
		"# besht:" + srcPath + ":2:1",
		"printf '%s\\n' \"$name\"",
	}, "\n") + "\n"
	calls := make(map[string]int)
	highlight := func(code, language string) ([]string, error) {
		if strings.Contains(code, "# besht:") {
			return nil, fmt.Errorf("source map comments should not be highlighted as shell")
		}
		calls[language]++
		lines := splitLines(code)
		for i, line := range lines {
			lines[i] = "\x1b[31m" + line + "\x1b[0m"
		}
		return lines, nil
	}

	out, err := RenderWithOptions(compiled, 80, RenderOptions{Highlight: highlight})
	if err != nil {
		t.Fatalf("RenderWithOptions: %v", err)
	}
	if calls["TypeScript"] != 1 || calls["sh"] != 1 {
		t.Fatalf("highlight calls: got %#v, want TypeScript=1 and sh=1", calls)
	}
	if !strings.Contains(out, "\x1b[31m") {
		t.Fatalf("rendered output should include ANSI color sequences:\n%s", out)
	}
	plain := stripANSI(out)
	if strings.Contains(plain, "# besht:") {
		t.Fatalf("rendered output should hide source comments:\n%s", plain)
	}
	if !strings.Contains(plain, "1 | let name = \"Ada\"") || !strings.Contains(plain, "3 | printf '%s\\n' \"$name\"") {
		t.Fatalf("rendered output should preserve side-by-side content after stripping ANSI:\n%s", plain)
	}
}

func TestANSIWidthHelpersIgnoreEscapeSequences(t *testing.T) {
	colored := "\x1b[31mabcdef\x1b[0m"
	if got := visibleLen(colored); got != 6 {
		t.Fatalf("visibleLen: got %d, want 6", got)
	}
	if got := stripANSI(padRight("\x1b[31mabc\x1b[0m", 5)); got != "abc  " {
		t.Fatalf("padRight with ANSI: got %q, want %q", got, "abc  ")
	}
	if got := stripANSI(truncate(colored, 4)); got != "abc>" {
		t.Fatalf("truncate with ANSI: got %q, want %q", got, "abc>")
	}
}

func TestNewBatHighlighterUsesBatWhenAvailable(t *testing.T) {
	highlight, ok := NewBatHighlighter()
	if !ok {
		t.Skip("bat is not installed")
	}
	ts, err := highlight("let x = 1\n", "TypeScript")
	if err != nil {
		t.Fatalf("TypeScript highlight: %v", err)
	}
	sh, err := highlight("printf '%s\\n' hi\n", "sh")
	if err != nil {
		t.Fatalf("shell highlight: %v", err)
	}
	if !strings.Contains(strings.Join(ts, "\n"), "\x1b[") || !strings.Contains(strings.Join(sh, "\n"), "\x1b[") {
		t.Fatalf("bat output should contain ANSI sequences, got ts=%q sh=%q", ts, sh)
	}
}

func lineIndexContaining(lines []string, needle string) int {
	for i, line := range lines {
		if strings.Contains(line, needle) {
			return i
		}
	}
	return -1
}

func countLinesContaining(lines []string, needle string) int {
	count := 0
	for _, line := range lines {
		if strings.Contains(line, needle) {
			count++
		}
	}
	return count
}
