package viewer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/victor141516/besht/internal/codegen"
)

func TestRenderHidesSourceCommentsAndLeavesGapForExpandedSourceLine(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "main.bsh")
	if err := os.WriteFile(srcPath, []byte("if (ready) console.log(\"yes\")\nconsole.log(\"done\")\n"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	compiled := strings.Join([]string{
		"# Generated by besht -- do not edit by hand",
		"# besht:" + srcPath + ":1:1",
		"# besht:" + srcPath + ":1:1",
		"if [ \"$ready\" = 1 ]; then",
		"    printf '%s\\n' 'yes'",
		"else",
		"    :",
		"fi",
		"# besht:" + srcPath + ":2:1",
		"printf '%s\\n' 'done'",
	}, "\n") + "\n"

	out, err := Render(compiled, 100)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if strings.Contains(out, "# besht:") {
		t.Fatalf("rendered output should hide source comments:\n%s", out)
	}
	lines := strings.Split(strings.TrimSuffix(out, "\n"), "\n")
	firstSourceIndex := lineIndexContaining(lines, "if (ready) console.log")
	secondSourceIndex := lineIndexContaining(lines, "console.log(\"done\")")
	if firstSourceIndex < 0 || secondSourceIndex < 0 {
		t.Fatalf("rendered output missing source lines:\n%s", out)
	}
	if secondSourceIndex-firstSourceIndex <= 1 {
		t.Fatalf("expanded source line should leave a left-side gap before the next source line:\n%s", out)
	}
	if countLinesContaining(lines, "if (ready) console.log") != 1 {
		t.Fatalf("duplicate same-line source comments should collapse into one source row:\n%s", out)
	}
	if !strings.Contains(out, "1 | if (ready) console.log") || !strings.Contains(out, "2 | console.log(\"done\")") {
		t.Fatalf("rendered output should include source line numbers:\n%s", out)
	}
	if !strings.Contains(out, "2 | if [ \"$ready\" = 1 ]; then") || !strings.Contains(out, "7 | printf '%s\\n' 'done'") {
		t.Fatalf("rendered output should include visible shell line numbers:\n%s", out)
	}
}

func TestBuildUsesSourceMapsInternallyButDoesNotDisplayThem(t *testing.T) {
	dir := t.TempDir()
	srcPath := filepath.Join(dir, "main.bsh")
	if err := os.WriteFile(srcPath, []byte("let name = \"Ada\"\nconsole.log(name)\n"), 0644); err != nil {
		t.Fatalf("write source: %v", err)
	}

	out, err := Build(srcPath, codegen.Options{NoSourceMap: true}, 100)
	if err != nil {
		t.Fatalf("Build: %v", err)
	}
	if strings.Contains(out, "# besht:") {
		t.Fatalf("visualization should not display source comments:\n%s", out)
	}
	if !strings.Contains(out, "1 | let name = \"Ada\"") || !strings.Contains(out, "2 | console.log(name)") {
		t.Fatalf("visualization should map source lines even when NoSourceMap is passed:\n%s", out)
	}
	if !strings.Contains(out, "name='Ada'") || !strings.Contains(out, "printf '%s\\n' \"$name\"") {
		t.Fatalf("visualization should include compiled shell lines:\n%s", out)
	}
}

func lineIndexContaining(lines []string, needle string) int {
	for i, line := range lines {
		if strings.Contains(line, needle) {
			return i
		}
	}
	return -1
}

func countLinesContaining(lines []string, needle string) int {
	count := 0
	for _, line := range lines {
		if strings.Contains(line, needle) {
			count++
		}
	}
	return count
}
