#!/bin/sh
# Generated by besht — do not edit by hand


# --- module: b_dep ---
b_dep__cmd='echo'
b_dep__param1='hello'
b_dep__param2='world'

# --- module: b ---
"$b_dep__cmd" "$b_dep__param1" "$b_dep__param2" | 'grep' 'hello'

