package stdlib

const Declarations = `// Generated by besht init.
// Place this file next to your entry .bsh file.
// Besht auto-loads entry-directory stdlib.d.bsh for compile, --split, and --check.

declare function file_exists(path: string): boolean
declare function is_dir(path: string): boolean
declare function is_readable(path: string): boolean
declare function is_writable(path: string): boolean
declare function is_executable(path: string): boolean
declare function is_empty(value: string): boolean
declare function is_set(value: string): boolean

declare const Besht: {
    conditions: {
        fileExists(path: string): boolean
        isDir(path: string): boolean
        isReadable(path: string): boolean
        isWritable(path: string): boolean
        isExecutable(path: string): boolean
        isEmpty(value: string): boolean
        isSet(value: string): boolean
    }
}

declare function len(values: string[]): number
declare function head(values: string[]): string
declare function tail(values: string[]): string[]
declare function append(values: string[], value: string): string[]
declare function contains(values: string[], value: string): boolean
declare function concat(left: string[], right: string[]): string[]
declare function range(start: number, end: number): number[]

declare function env(name: string): string
declare function env(name: string, defaultValue: string): string
interface FetchResponse {
    text(): string
}
declare function fetch(url: string): FetchResponse
declare function to_str(value: string): string
declare function to_int(value: string): number
declare function String(value: string): string
declare function Boolean(value): boolean
declare function exit()
declare function exit(code: number)
declare function exit(code: status)

declare const process: {
    env: Record<string, string>
    exit(): void
    exit(code: number): void
    exit(code: status): void
}

declare const args: {
    argv(): string[]
    positional(index: number): string
    option(longName: string, shortName: string): string
    flag(longName: string, shortName: string): boolean
}

declare namespace console {
    function log(value: string): void
    function error(value: string): void
}

declare namespace Number {
    function parseInt(value: string, radix: number): number
    function parseFloat(value: string): number
    function isFinite(value: number): boolean
    function isInteger(value: number): boolean
    function isSafeInteger(value: number): boolean
    function isNaN(value: number): boolean
}

declare namespace Math {
    function min(left: number, right: number): number
    function max(left: number, right: number): number
    function round(value: number): number
    function floor(value: number): number
    function ceil(value: number): number
    function trunc(value: number): number
    function abs(value: number): number
    function sign(value: number): number
    function pow(base: number, exponent: number): number
    function sqrt(value: number): number
}

declare namespace Array {
    function from(source: { length: number }): number[]
    function of(first: string, second: string): string[]
    function isArray(value): boolean
}

declare namespace Object {
    function keys(value: object): string[]
    function values(value: object): string[]
    function entries(value: object): string[][]
    function hasOwn(value: object, key: string): boolean
}
`
