package stdlib

const Declarations = `// Generated by besht init.
// Place this file next to your entry .bsh file.
// Besht auto-loads entry-directory stdlib.d.bsh for compile, --split, and --check.

declare const Besht: {
    fs: {
        isFile(path: string): boolean
        isDir(path: string): boolean
        isReadable(path: string): boolean
        isWritable(path: string): boolean
        isExecutable(path: string): boolean
    }
    strings: {
        isEmpty(value: string): boolean
        isNonEmpty(value: string): boolean
    }
    args: {
        argv(): string[]
        positional(index: number): string
        option(longName: string, shortName: string): string
        flag(longName: string, shortName: string): boolean
    }
    iter: {
        range(start: number, end: number): number[]
    }
}

interface FetchResponse {
    text(): string
}
declare function fetch(url: string): FetchResponse
declare function Boolean(value): boolean
type JSONValue = string

declare const process: {
    env: Record<string, string>
    exit(): void
    exit(code: number): void
    exit(code: status): void
}

declare namespace console {
    function log(value: string): void
    function error(value: string): void
}

declare namespace Number {
    function parseInt(value: string, radix: number): number
    function parseFloat(value: string): number
    function isFinite(value: number): boolean
    function isInteger(value: number): boolean
    function isSafeInteger(value: number): boolean
    function isNaN(value: number): boolean
}

declare namespace Math {
    function min(left: number, right: number): number
    function max(left: number, right: number): number
    function round(value: number): number
    function floor(value: number): number
    function ceil(value: number): number
    function trunc(value: number): number
    function abs(value: number): number
    function sign(value: number): number
    function pow(base: number, exponent: number): number
    function sqrt(value: number): number
}

declare namespace Array {
    function from(source: { length: number }): number[]
    function from(source: string): string[]
    function of(first: string, second: string): string[]
    function isArray(value): boolean
}

declare namespace Object {
    function keys(value: object): string[]
    function values(value: object): string[]
    function entries(value: object): string[][]
    function fromEntries(entries: string[][]): object
    function hasOwn(value: object, key: string): boolean
    function assign(target: object): object
    function assign(target: object, source: object): object
}

declare namespace JSON {
    function parse(value: string): JSONValue
    function stringify(value: string): string
    function stringify(value: number): string
    function stringify(value: boolean): string
    function stringify(value: JSONValue): string
    function stringify(value: string[]): string
    function stringify(value: number[]): string
    function stringify(value: boolean[]): string
    function stringify(value: object): string
}
`
